version: '2'
services:

  web:
    image: docker-registry.local/foolishness/web:latest
    restart: always
    ports: 
      - 80:80
    depends_on:
      - front-api-node

  front-api-node:
    image: docker-registry.local/foolishness/front-api-node:latest
    restart: always
    depends_on:
      - back-api-go
      - back-api-php
      - back-api-java

  back-api-go:
    image: docker-registry.local/foolishness/back-api-go:latest
    restart: always
    depends_on:
      - mongodb
    
  back-api-php:
    image: docker-registry.local/foolishness/back-api-php:latest
    restart: always
    depends_on:
      - mongodb
    
  back-api-java:
    image: docker-registry.local/foolishness/back-api-java:latest
    restart: always
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

#  desktop:
#    image: sergioortegagomez/docker-ubuntu-cucumber
#    restart: always
#    ports:
#      - 3389:3389
#    environment:
#      - DESKTOP=true