version: '2'
services:

  web:
    image: foolishness/web:latest
    ports: 
      - 80:80
    depends_on: 
      - front-api-node

  front-api-node:
    image: foolishness/front-api-node:latest
    ports:
      - 3000:3000
    depends_on:
      - back-api-go
      - back-api-php
      - back-api-java

  back-api-go:
    image: foolishness/back-api-go:latest
    depends_on:
      - mongodb
    
  back-api-php:
    image: foolishness/back-api-php:latest
    depends_on:
      - mongodb
    
  back-api-java:
    image: foolishness/back-api-java:latest
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo:latest

  desktop:
    image: sergioortegagomez/docker-ubuntu-cucumber
    ports:
      - 3389:3389
    environment:
      - DESKTOP=true