version: '3'
services:

  front-api-node:
    build: src/front-api-node
    ports:
      - 80:3000
    depends_on:
      - back-api-go
      - back-api-php

  back-api-go:
    build: src/back-api-go
    #ports:
    #  - 1100:3000

  back-api-php:
    build: src/back-api-php
    #ports:
    #  - 1101:80
  
  back-api-java:
    build: src/back-api-java
    #ports:
    #  - 1102:8080