version: '3'
services:

  gatling-runner:
    image: denvazh/gatling:3.2.1
    command: [-s, simulations.BasicSimulation]
    volumes:
    - ./gatling/simulations:/opt/gatling/user-files/simulations
    #- ./gatling/results:/opt/gatling/results