version: '2'
services:

  web:
    image: localhost:5000/foolishness/web:latest
    restart: always
    pull_policy: never
    ports:
      - 80:80
    depends_on:
      #- back-api-go
      - back-api-node
      - back-api-java
    networks:
      - app  

  #back-api-go:
  #  image: localhost:5000/foolishness/back-api-go:latest
  #  restart: always
  #  pull_policy: never
  #  networks:
  #    - app
    
  back-api-node:
    image: localhost:5000/foolishness/back-api-node:latest
    restart: always
    pull_policy: never
    ports:
      - 10001:80
    networks:
      - app
    
  back-api-java:
    image: localhost:5000/foolishness/back-api-java:latest
    restart: always
    pull_policy: never
    networks:
      - app
    
networks:
  app: