apiVersion: v1
kind: Service
metadata:
  labels:
    foolishness.service: back-api-php
  name: back-api-php
  namespace: foolishness
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    foolishness.service: back-api-php
status:
  loadBalancer: {}
