apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    foolishness.service: back-api-php
  name: back-api-php
  namespace: foolishness
spec:
  replicas: 1
  selector:
    matchLabels:
      foolishness.service: back-api-php
  strategy: {}
  template:
    metadata:
      labels:
        foolishness.service: back-api-php
    spec:
      containers:
      - image: localhost:5000/foolishness/back-api-php:latest
        imagePullPolicy: ""
        name: back-api-php
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""  
status: {}
