apiVersion: v1
kind: Service
metadata:
  labels:
    foolishness.service: back-api-java
  name: back-api-java
  namespace: foolishness
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    foolishness.service: back-api-java
status:
  loadBalancer: {}
