apiVersion: v1
kind: Service
metadata:
  labels:
    foolishness.service: front-api-node
  name: front-api-node
  namespace: foolishness
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    foolishness.service: front-api-node
status:
  loadBalancer: {}
