apiVersion: v1
kind: Service
metadata:
  labels:
    foolishness.service: front-api-node
  name: front-api-node
  namespace: foolishness
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    foolishness.service: front-api-node
status:
  loadBalancer: {}
