apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    foolishness.service: web
  name: web
  namespace: foolishness
spec:
  replicas: 1
  selector:
    matchLabels:
      foolishness.service: web
  strategy: {}
  template:
    metadata:
      labels:
        foolishness.service: web
    spec:
      containers:
      - image: localhost:5000/foolishness/web:latest
        imagePullPolicy: ""
        name: web
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
